# Generated by Django 4.2.16 on 2025-08-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
